//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Somatic.Assets.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Somatic.Assets.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string CompCtrl_delete {
            get {
                return ResourceManager.GetString("CompCtrl_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desplegar.
        /// </summary>
        internal static string CompCtrl_deploy {
            get {
                return ResourceManager.GetString("CompCtrl_deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bajar.
        /// </summary>
        internal static string CompCtrl_down {
            get {
                return ResourceManager.GetString("CompCtrl_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloquear.
        /// </summary>
        internal static string CompCtrl_lock {
            get {
                return ResourceManager.GetString("CompCtrl_lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replegar.
        /// </summary>
        internal static string CompCtrl_retract {
            get {
                return ResourceManager.GetString("CompCtrl_retract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloquear.
        /// </summary>
        internal static string CompCtrl_unlock {
            get {
                return ResourceManager.GetString("CompCtrl_unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir.
        /// </summary>
        internal static string CompCtrl_up {
            get {
                return ResourceManager.GetString("CompCtrl_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección de Carpeta.
        /// </summary>
        internal static string FldCtrl_tooltip {
            get {
                return ResourceManager.GetString("FldCtrl_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una Carpeta....
        /// </summary>
        internal static string FoldCtrl_choose {
            get {
                return ResourceManager.GetString("FoldCtrl_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string Logg_clear {
            get {
                return ResourceManager.GetString("Logg_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Logg_error {
            get {
                return ResourceManager.GetString("Logg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info.
        /// </summary>
        internal static string Logg_info {
            get {
                return ResourceManager.GetString("Logg_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logger.
        /// </summary>
        internal static string Logg_title {
            get {
                return ResourceManager.GetString("Logg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        internal static string Logg_warn {
            get {
                return ResourceManager.GetString("Logg_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Componente Script.
        /// </summary>
        internal static string Script_title {
            get {
                return ResourceManager.GetString("Script_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar....
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir entidad.
        /// </summary>
        internal static string SETC_addentity {
            get {
                return ResourceManager.GetString("SETC_addentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar entidad.
        /// </summary>
        internal static string SETC_removeentity {
            get {
                return ResourceManager.GetString("SETC_removeentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renombrar entidad.
        /// </summary>
        internal static string SETC_renameentity {
            get {
                return ResourceManager.GetString("SETC_renameentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renombrar escena.
        /// </summary>
        internal static string SETC_renamescene {
            get {
                return ResourceManager.GetString("SETC_renamescene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        internal static string Transform_position {
            get {
                return ResourceManager.GetString("Transform_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotación.
        /// </summary>
        internal static string Transform_rotation {
            get {
                return ResourceManager.GetString("Transform_rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escala.
        /// </summary>
        internal static string Transform_scale {
            get {
                return ResourceManager.GetString("Transform_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Componente Transformación.
        /// </summary>
        internal static string Transform_title {
            get {
                return ResourceManager.GetString("Transform_title", resourceCulture);
            }
        }
    }
}
