//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Somatic.Assets.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Somatic.Assets.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string Button_accept {
            get {
                return ResourceManager.GetString("Button_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Button_cancel {
            get {
                return ResourceManager.GetString("Button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portapapeles.
        /// </summary>
        internal static string Clip_title {
            get {
                return ResourceManager.GetString("Clip_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string CompCtrl_delete {
            get {
                return ResourceManager.GetString("CompCtrl_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desplegar.
        /// </summary>
        internal static string CompCtrl_deploy {
            get {
                return ResourceManager.GetString("CompCtrl_deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bajar.
        /// </summary>
        internal static string CompCtrl_down {
            get {
                return ResourceManager.GetString("CompCtrl_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloquear.
        /// </summary>
        internal static string CompCtrl_lock {
            get {
                return ResourceManager.GetString("CompCtrl_lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replegar.
        /// </summary>
        internal static string CompCtrl_retract {
            get {
                return ResourceManager.GetString("CompCtrl_retract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloquear.
        /// </summary>
        internal static string CompCtrl_unlock {
            get {
                return ResourceManager.GetString("CompCtrl_unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir.
        /// </summary>
        internal static string CompCtrl_up {
            get {
                return ResourceManager.GetString("CompCtrl_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string CrPr_configuration {
            get {
                return ResourceManager.GetString("CrPr_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string CrPr_description {
            get {
                return ResourceManager.GetString("CrPr_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motor.
        /// </summary>
        internal static string CrPr_engine {
            get {
                return ResourceManager.GetString("CrPr_engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo del Motor.
        /// </summary>
        internal static string CrPr_engineMode {
            get {
                return ResourceManager.GetString("CrPr_engineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carpeta.
        /// </summary>
        internal static string CrPr_folder {
            get {
                return ResourceManager.GetString("CrPr_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string CrPr_name {
            get {
                return ResourceManager.GetString("CrPr_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string CrPr_project {
            get {
                return ResourceManager.GetString("CrPr_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Proyecto.
        /// </summary>
        internal static string CrPr_title {
            get {
                return ResourceManager.GetString("CrPr_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explorador de Archivos.
        /// </summary>
        internal static string FiEx_title {
            get {
                return ResourceManager.GetString("FiEx_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección de Carpeta.
        /// </summary>
        internal static string FldCtrl_tooltip {
            get {
                return ResourceManager.GetString("FldCtrl_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una Carpeta....
        /// </summary>
        internal static string FoldCtrl_choose {
            get {
                return ResourceManager.GetString("FoldCtrl_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string Info_active {
            get {
                return ResourceManager.GetString("Info_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Info_name {
            get {
                return ResourceManager.GetString("Info_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string Info_title {
            get {
                return ResourceManager.GetString("Info_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string Logg_clear {
            get {
                return ResourceManager.GetString("Logg_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Logg_error {
            get {
                return ResourceManager.GetString("Logg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info.
        /// </summary>
        internal static string Logg_info {
            get {
                return ResourceManager.GetString("Logg_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logger.
        /// </summary>
        internal static string Logg_title {
            get {
                return ResourceManager.GetString("Logg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        internal static string Logg_warn {
            get {
                return ResourceManager.GetString("Logg_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un problema con el archivo:.
        /// </summary>
        internal static string Msg_badfile {
            get {
                return ResourceManager.GetString("Msg_badfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar el archivo de configuración.
        /// </summary>
        internal static string Msg_notconfig {
            get {
                return ResourceManager.GetString("Msg_notconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra la carpeta:.
        /// </summary>
        internal static string Msg_notfolder {
            get {
                return ResourceManager.GetString("Msg_notfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido guardar la configuración.
        /// </summary>
        internal static string Msg_notwrite {
            get {
                return ResourceManager.GetString("Msg_notwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Entidad.
        /// </summary>
        internal static string NewEntity {
            get {
                return ResourceManager.GetString("NewEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NuevoProyecto.
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NuevaEscena.
        /// </summary>
        internal static string NewScene {
            get {
                return ResourceManager.GetString("NewScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string OpPr_description {
            get {
                return ResourceManager.GetString("OpPr_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string OpPr_name {
            get {
                return ResourceManager.GetString("OpPr_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Nuevo Proyecto.
        /// </summary>
        internal static string OpPr_newProject {
            get {
                return ResourceManager.GetString("OpPr_newProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta.
        /// </summary>
        internal static string OpPr_path {
            get {
                return ResourceManager.GetString("OpPr_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir Proyecto.
        /// </summary>
        internal static string OpPr_Title {
            get {
                return ResourceManager.GetString("OpPr_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto ya existe.
        /// </summary>
        internal static string Rule_exists {
            get {
                return ResourceManager.GetString("Rule_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La carpeta ya existe.
        /// </summary>
        internal static string Rule_folderexists {
            get {
                return ResourceManager.GetString("Rule_folderexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo es obligatorio.
        /// </summary>
        internal static string Rule_mandatory {
            get {
                return ResourceManager.GetString("Rule_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay caracteres no válidos.
        /// </summary>
        internal static string Rule_nomatch {
            get {
                return ResourceManager.GetString("Rule_nomatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Componente Script.
        /// </summary>
        internal static string Script_title {
            get {
                return ResourceManager.GetString("Script_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar....
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir entidad.
        /// </summary>
        internal static string SETC_addentity {
            get {
                return ResourceManager.GetString("SETC_addentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar entidad.
        /// </summary>
        internal static string SETC_removeentity {
            get {
                return ResourceManager.GetString("SETC_removeentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renombrar entidad.
        /// </summary>
        internal static string SETC_renameentity {
            get {
                return ResourceManager.GetString("SETC_renameentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renombrar escena.
        /// </summary>
        internal static string SETC_renamescene {
            get {
                return ResourceManager.GetString("SETC_renamescene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        internal static string Transform_position {
            get {
                return ResourceManager.GetString("Transform_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotación.
        /// </summary>
        internal static string Transform_rotation {
            get {
                return ResourceManager.GetString("Transform_rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escala.
        /// </summary>
        internal static string Transform_scale {
            get {
                return ResourceManager.GetString("Transform_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Componente Transformación.
        /// </summary>
        internal static string Transform_title {
            get {
                return ResourceManager.GetString("Transform_title", resourceCulture);
            }
        }
    }
}
